import com.mysql.jdbc.Connection;
import java.sql.JDBCType;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sİnan
 */
public class sanatci extends javax.swing.JFrame {

    /**
     * Creates new form sanatci
     */
    public sanatci() {
        initComponents();
        TabloDoldur();
    }
    
    public void TabloDoldur(){
        Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
          ResultSet rs = null;
        try {
            connect = db.getConnection();
            String sql="select distinct sanatcitablo.sanatciadi,sanatcitablo.sanatciulke from sanatcitablo";
            statement=connect.prepareStatement(sql);
             rs = statement.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel (rs));
             connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
     public void  UyrukUpdate (String sanatciadi,String uyruk) throws SQLException{
         Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
         
         try{
         connect = db.getConnection();
         String sql="Update sanatcitablo set sanatciulke='"+uyruk+"' where sanatciadi='"+sanatciadi+"'";
         statement=connect.prepareStatement(sql);
         statement.executeUpdate();
         JOptionPane.showMessageDialog(null,"Sanatçı Başarıyla Güncellendi");
         }catch(SQLException exception){
             db.ShowError(exception);
             JOptionPane.showMessageDialog(null,"Sanatçı Güncellenemedi");
         }finally{
             statement.close();
             connect.close();
         }
      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dönme = new javax.swing.JButton();
        uyruk = new javax.swing.JButton();
        sanatci_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uyruk_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(187, 34, 550, 202);

        dönme.setBackground(new java.awt.Color(153, 255, 255));
        dönme.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        dönme.setText("ÖNCEKI EKRANA DÖN");
        dönme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dönmeActionPerformed(evt);
            }
        });
        getContentPane().add(dönme);
        dönme.setBounds(833, 34, 207, 42);

        uyruk.setBackground(new java.awt.Color(255, 204, 0));
        uyruk.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        uyruk.setText("UYRUK EKLE");
        uyruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyrukActionPerformed(evt);
            }
        });
        getContentPane().add(uyruk);
        uyruk.setBounds(833, 136, 207, 42);

        sanatci_txt.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        sanatci_txt.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(sanatci_txt);
        sanatci_txt.setBounds(300, 300, 390, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setText("Sanatçı Uyruk:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(187, 355, 109, 25);

        uyruk_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyruk_txtActionPerformed(evt);
            }
        });
        getContentPane().add(uyruk_txt);
        uyruk_txt.setBounds(301, 356, 550, 22);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setText("Sanatçı Adı:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(187, 312, 109, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arkaplanı.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1170, 850);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1170, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dönmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dönmeActionPerformed
        admin menu4 = new admin();
        menu4.setSize(1172, 787);
        menu4.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_dönmeActionPerformed

    private void uyrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyrukActionPerformed
        
        String sanatciadi= jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();     
        String uyruk=uyruk_txt.getText();
            
        try {
            UyrukUpdate(sanatciadi, uyruk);
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            TabloDoldur();
    }//GEN-LAST:event_uyrukActionPerformed

    private void uyruk_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyruk_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyruk_txtActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        sanatci_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        uyruk_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        
        
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sanatci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dönme;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel sanatci_txt;
    private javax.swing.JButton uyruk;
    private javax.swing.JTextField uyruk_txt;
    // End of variables declaration//GEN-END:variables
}
